[package]
name = "microgifter-homeserver-control-center"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "microgifter_homeserver_control_center_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64.workspace = true
futures-util.workspace = true
microgifter-homeserver-core = { path = "../crates/homeserver-core" }
reqwest.workspace = true
rfd.workspace = true
serde.workspace = true
tauri = { version = "2", features = [] }
tokio.workspace = true
tokio-util.workspace = true
zeroize.workspace = true
