[package]
name = "keyring"
version = "3.6.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "keyring"
path = "src/lib.rs"

[dependencies]
sha2.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
