[package]
name = "microgifter-homeserver-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "microgifter-homeserver-service"
path = "src/main.rs"

[dependencies]
aes-gcm.workspace = true
anyhow.workspace = true
argon2.workspace = true
axum.workspace = true
base64.workspace = true
chrono.workspace = true
directories.workspace = true
ed25519-dalek.workspace = true
flate2.workspace = true
futures-util.workspace = true
hex.workspace = true
microgifter-homeserver-core = { path = "../homeserver-core" }
rand.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows-service = "0.8"
windows-sys.workspace = true
